[main]
summary=Standalone Low Latency Gaming Profile (Optimized)

[cpu]
enabled=1
governor=performance
energy_perf_bias=performance
#Setting turbo ON and then change pstate to not allow full turbo for better thermals
no_turbo=1
force_latency=1
energy_performance_preference=performance

[disk]
devices=nvme*
scheduler=none
readahead=128

[sysfs]
# Around 3600mhz to 3800mhz
/sys/devices/system/cpu/intel_pstate/min_perf_pct=70
/sys/devices/system/cpu/intel_pstate/max_perf_pct=80

/sys/kernel/mm/transparent_hugepage/enabled=madvise
/sys/kernel/mm/transparent_hugepage/defrag=madvise

/sys/devices/system/cpu/cpu*/power/pm_qos_resume_latency_us=0
/sys/module/pcie_aspm/parameters/policy=performance

[script]
#place in /etc/tuned/profiles/<PROFILENAME>/script.sh
script=script.sh

[sysctl]
vm.swappiness=1
vm.compaction_proactiveness=0
vm.dirty_ratio=10
vm.dirty_background_ratio=3
vm.page-cluster=0

kernel.numa_balancing=0
kernel.sched_min_granularity_ns=1000000
kernel.sched_wakeup_granularity_ns=1500000
kernel.sched_migration_cost_ns=500000
kernel.sched_autogroup_enabled=0

# NETWORK
net.core.netdev_max_backlog=5000
net.ipv4.tcp_low_latency=1
net.ipv4.tcp_slow_start_after_idle=0
net.core.default_qdisc=fq_codel
net.core.rmem_max=16777216
net.core.wmem_max=16777216
